name: CI LP Angular Cypress

on:
  pull_request:
  workflow_dispatch:

jobs:
  lp-angular-cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        containers: [1, 2]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Create emulator data directory
        run: mkdir -p functions/emulator/
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:lp, npm --prefix ./functions run build:watch, npm --prefix ./functions run emulate
          wait-on: 'http://localhost:4202, http://localhost:4000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
