name: CI Web Angular E2E

on:
  pull_request:
  workflow_dispatch:

jobs:
  web-angular-e2e:
    runs-on: ubuntu-latest

    environment:
      name: testnet

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json

      - name: Create environment file's directory
        run: mkdir -p ./projects/web/src/environments
      - name: Create empty environment file
        run: touch ./projects/web/src/environments/environment.ts
      - name: Create empty environment file for development
        run: touch ./projects/web/src/environments/environment.development.ts
      - name: Restore environment file content from Repository secrets
        env:
          ANGULAR_WEB_ENVIRONMENT: ${{ secrets.ANGULAR_WEB_ENVIRONMENT_TESTNET_DEV }}
        run: echo $ANGULAR_WEB_ENVIRONMENT | base64 --decode --ignore-garbage > ./projects/web/src/environments/environment.development.ts

      - run: npm ci
      - run: npm run e2e:web:ci
      - run: rm ./projects/web/src/environments/environment.development.ts
